// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruubjafeycycfnniqqvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1dWJqYWZleWN5Y2ZubmlxcXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMzkzMTcsImV4cCI6MjA2ODcxNTMxN30.dJaVNNwDYhIW3BGhao2GzMwQTUwgRs4bdKtRzV1qVVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});